# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93d93021e13c542ef9334d952391097a4f5221889f89115506c719aa092463e0dad39de6b0b411690351849833d91081a3665c0262795aba5be82a0f0371fbe6

test:
  secret_key_base: 8733f29964c6528b87ea3f238de65dcefce104cad49d4feb657099c04bc82047741278a4dd0cb7377a69857358aea455423c27f4d63a3bb6342ce9ca61d3da41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
